### ISSUE TITLE
[BUG]: Very small display when the resolution is too large

### ISSUE THREAD

**Issue by GiaGui** [KomodoPlatform/komodo-wallet#1365]
**Describe the bug**
The application displays badly when the computer monitor is a television (I think the issue is related to the resolution of my monitor).
When I launch the application, all of the displays are unreadable because they are displayed in very small size. Likewise, all of the buttons are extremely small.
![login](https://user-images.githubusercontent.com/70819195/136691857-b5658af7-47fd-451f-8bf5-093a8b38211a.png)
![dashboard](https://user-images.githubusercontent.com/70819195/136691859-953399ff-ebf0-4d0d-ac5a-fc5a332d0c57.png)
![pro](https://user-images.githubusercontent.com/70819195/136691860-30414d4e-2912-4723-b759-3ecbf753781b.png)
![simple](https://user-images.githubusercontent.com/70819195/136691862-42d7ea9b-7e80-4e4e-aa77-fc790e047003.png)

**To Reproduce**
1. Have a monitor with a resolution of 3840 x 2160
2. Try to use ADEX

**Expected behavior**
Regardless of the monitor resolution, the application should display correctly, text should be legible, buttons should be of sufficient size, windows should be of properly proportioned dimensions, and empty spaces between windows should not be so big.

**Screenshots**

**Desktop (please complete the following information):**
OS: WIN 10 Pro
Monitor: Android TV 55 '' (brand: TCL)
Display specifications: Recommended resolution 3840 x 2160
ADEX version: atomicdex-desktop-0.5.2-beta-windows-portable
![sys info](https://user-images.githubusercontent.com/70819195/136691722-3a786c64-e964-40e5-8276-1ac9fd810dda.png)
![display info](https://user-images.githubusercontent.com/70819195/136691740-0896eca9-49d1-44ec-aed8-033a607159e4.png)

**Comment by samurai321** [comment]
right, i can confirm this is an issue, the only way to fix it right now, is to change the resolution to something like 1920x1080p and restart the program. thats the highest resolution that is usable.

Maybe an option to make everything inside the window 1.5x and 2x .

**Comment by smk762** [comment]
cc: @cipig

**Comment by cipig** [comment]
![image](https://user-images.githubusercontent.com/32116761/161391863-bdcbdd1b-2e37-44b4-a338-f0f0c3567d01.png)

this is how the new design looks on full screen (3840x2160)
would be nice if the chart would resize too... making orderbook/best orders too wide does not look very good :-)

**Comment by smk762** [comment]
Suggestions:
- Move exchange rates statusbar into the "Place Order" panel, beneath "use custom minimum trade amount" checkbox. Move exchange rate text into a tooltip on statusbar mouseover
![image](https://user-images.githubusercontent.com/35845239/161392330-ce0249ab-1e14-40db-8e5b-ddb7dc261617.png)
- Move "Best orders" and "Orderbook" into tabs within "Trading Information" area, allowing this area to become wider. In this case, Buy / Sell sections could be side by side rather than stacked top / bottom. This would also allow for wider combo selectors, overcoming https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1706
- Let chart fill all available space on x-axis (full_width - order_form_width)
- Set chart and trading info area to default to 50% of [full_height - combo_selectors_height], autoexpanding to fill when either is hidden or collapsed
- Perhaps also combine the Orders / History tabs into a single tab. Status column effectively communicates whether "maker order pending" / "order in progress" / "swap complete" / "swap failed"

I can mock up a crude photoshop of this concept if others think it has potential merit.

**Comment by himu007** [comment]
> Suggestions:
> 
> * Move exchange rates statusbar into the "Place Order" panel, beneath "use custom minimum trade amount" checkbox. Move exchange rate text into a tooltip on statusbar mouseover
> * Move "Best orders" and "Orderbook" into tabs within "Trading Information" area, allowing this area to become wider. In this case, Buy / Sell sections could be side by side rather than stacked top / bottom. This would also allow for wider combo selectors, overcoming [Improve Combobox selectors #1706](https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1706)
> * Let chart fill all available space on x-axis (full_width - order_form_width)
> * Set chart and trading info area to default to 50% of [full_height - combo_selectors_height], autoexpanding to fill when either is hidden or collapsed
> * Perhaps also combine the Orders / History tabs into a single tab. Status column effectively communicates whether "maker order pending" / "order in progress" / "swap complete" / "swap failed"
> 
> I can mock up a crude photoshop of this concept if others think it has potential merit.

or make all those sections user configurable depending on their monitor. like widgets. user can setup the widget to fill up their screen as they see fit and suits their trading needs.
there can be many different widgets.
i.e: `maker orders`, `ongoing swaps`, `history`, `failed swap`(only for the stuck funds one, so user know which funds they should recover) and one with all of them combined. so, depending on screen resolution user can decide what they would like.

but, on a big screen, the app doesn't look beautiful currently.

**Comment by smk762** [comment]
Issue reported as still existing by @gcharang, seems to affect 4K displays with scaling applied. 
TODO:
- [ ] detect user res and scaling factor
- [ ] apply scaling factor to all fonts and fixed size components
- [ ] test a variety of scale / res combinations to confirm no regression.
