### ISSUE TITLE
[FEATURE REQUEST]: B2C options for AtomicDex

### ISSUE THREAD

**Issue by RoyHolzem** [KomodoPlatform/komodo-wallet#1552]
**Is your feature request related to a problem? Please describe.**
AtomicDex has no B2C options. (1 entity manage multiple wallets)

**Describe the solution you'd like**
Enable "Business Mode" in AtomicDex which unlocks "Client Wallets" where you can: 
- Add new client
- Edit existing client
- Remove client
- Open client wallet

![New Business Mode Menu v2 0](https://user-images.githubusercontent.com/17780714/149070873-b0f90a8d-b0f8-48f5-9212-e67a4c2061b6.png)

Clicking on "Open" leads to that Client's wallet overview:

![Open leads to](https://user-images.githubusercontent.com/17780714/149071214-49e45a60-47f1-40c4-9411-93f991806f64.png)

**Describe alternatives you've considered**
There are none for B2C. Alternatives imply manual workarounds or leaving funds on CEX

**Comment by tonymorony** [comment]
Thank you for the issue opening!

It's quite a non-trivial task to implement trustless 3rd party portfolios management since wallets are non-custodial and seed possession (transactions singing possibility) means funds possession. 

If 3rd party persons trust your funds fully they can just share a seed with you ( = funds possession) and you can import this seed as another wallet with a name same as a client name, or you can pre-create a separate wallet yourself, they can send funds to you and control funds moving by address tracking. Most prob. it should be a trust-based system with contract signed and etc

**Comment by RoyHolzem** [comment]
> 

People outside of crypto want to move away from centralization yet lack technical capabilities to do so. 
B2C Wallet in this issue would vastly increase overall adoption. 

Right now the business process is:
You have to generate 1 Seed and install Adex on 1 seperate physical (not cloud = safety) micro machine (f.i. beelink) per client. 
Use KVMP switch to switch to the according client's wallet and make transaction X, Y.

No other alternative besides proposed solution in this issue fixes this problem natively.
