### ISSUE TITLE
[BUG]: wallet loads chart but doesn't show it

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/komodo-wallet#1711]
when switching between different coins on wallet page, the following log entry is shown:
```
[21:45:49] [debug] [main.prerequisites.hpp:86] [579675]: Wallet: Loading chart for BINANCE:AVAXUSD
```

there is no chart on wallet page, so no need to load one

**Comment by SylEze** [comment]
Charts are currently disabled on the wallet side because their style are too much different (trading view charts) from ADEX

We are planning to have our own chart component implemented

When implemented, it should by the same time fixes the following issue https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1473
