### ISSUE TITLE
[FEATURE REQUEST]: enable automatic merge of utxos

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/komodo-wallet#1784]
ADEX API supports automatic merging of utxos, like this: `curl --url "http://127.0.0.1:7783" --data "{\"method\":\"electrum\",\"coin\":\"RICK\",\"servers\":[{\"url\":\"electrum1.cipig.net:20017\",\"protocol\":\"SSL\"},{\"url\":\"electrum2.cipig.net:20017\",\"protocol\":\"SSL\"},{\"url\":\"electrum3.cipig.net:20017\",\"protocol\":\"SSL\"}],\"userpass\":\"$userpass\",\"mm2\":1,\"utxo_merge_params\":{\"merge_at\":200,\"check_every\":600,\"max_merge_at_once\":100}}"`

Can we please use this for all UTXO coins, except BTC (too high fees)?

Reason: If we don't do it and people have too many UTXOs, ADEX will stop working for that coin.

**Comment by smk762** [comment]
This should be optional, defaulting to off but configurable by user in settings.
Needs:
- [ ] Back end code for method / inputs / outputs
- [ ] Toggle in settings to activate (requires restart)
- [ ] Mention in docs so we can point support queries from miners related to this.

**Comment by smk762** [comment]
I'm not sure there is a viable gui solution for this issue without either more than ideal complexity (e.g. coin specific settings) or to broad (e.g. blanket application of the merge param).

It does need to be addressed though, as we regularly get people mining to their atomicdex wallet and accumulating thousands of utxos which they find difficult to consolidate. 

A negotiated solution with no impact on front end and minimal technical expertise by the user could be to allow this to be defined within a user's coins.json file - so that on activation, if these flags / values are present, the coin will be activated accordingly.

The process would be simple enough to document in a guide for reference whenever needed.

@cipig would this solution be acceptable?

**Comment by cipig** [comment]
the easiest solution would be to apply the merge params to all utxo coins
if you keep the values rather high like `\"merge_at\":200,\"check_every\":600,\"max_merge_at_once\":100}}"`, it will only affect the targeted users, since no normal user has 200 utxos in his address , i guess
txfee problems are only present with BTC utxos, all other coins have very low txfees, and nobody has 200 BTC utxos, at least not from mining :-)

but i am fine with any solution... we can start by adding the options to coins config in ADEX Desktop, so if they are present they are added to the enable/electrum call

**Comment by smk762** [comment]
The main problem with setting it by default is that it opens up potential perception of "unauthorised" transactions, and the user may experience confusion and think they have been hacked.

**Comment by cipig** [comment]
> The main problem with setting it by default is that it opens up potential perception of "unauthorised" transactions, and the user may experience confusion and think they have been hacked.

Sure, but it would "affect" only few users with `\"merge_at\":200` or higher.

**Comment by smk762** [comment]
I think we should maybe also add something that detects when there are > "x" utxos, and then show user a pop up warning which lets them toggle on utxo merging for the coin that needs it

**Comment by smk762** [comment]
This issue is still not solved in a convenient way (requires support guidance and manual config), and comes up every few weeks from a user mining directly to the wallet.
